Change open encoding to utf16
When trying to use file from winPEAS it failed to parse it to json because of:

```bash
Traceback (most recent call last):
  File "/peas2json.py", line 168, in <module>
    main()
    ~~~~^^
  File "/peas2json.py", line 148, in main
    for line in open(OUTPUT_PATH, 'r', encoding="utf8").readlines():
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

With utf16, there is no such problem